Description of IntervalSetToLogical
Home > @intervalSet > IntervalSetToLogical.m
IntervalSetToLogical
PURPOSE
Converts intervalset data into a long logical array where periods inside
SYNOPSIS
function boolean = IntervalsToLogical(is)
DESCRIPTION
 Converts intervalset data into a long logical array where periods inside
 any interval are 1 and outside interval are 0.
CROSS-REFERENCE INFORMATION
This function calls:
End Ending time of the intervalSet object
FirstTime First time of the intervalSet
LastTime Returns last time of an intervalSet
Start Starting times of for each interval in the set
length Returns the length of each interval in the set
subset Returns subsets of an intervalSet
This function is called by:
SOURCE CODE
function boolean = IntervalsToLogical(is)
% Converts intervalset data into a long logical array where periods inside
% any interval are 1 and outside interval are 0.
b = FirstTime(is);
e = LastTime(is);
boolean = b:e;
for a = 1:length(length(is));
    boolean(Start(subset(is,a)):End(subset(is,a))) = 1;
end