Description of plotIntervals
Home > @intervalSet > plotIntervals.m
plotIntervals
PURPOSE
% Plots a horizontal line showing timing of each interval in a set
SYNOPSIS
function plotIntervals(intervals)
DESCRIPTION
 % Plots a horizontal line showing timing of each interval in a set
 USAGE:
     plotIntervals(x)
 INPUT:
    x: intervalSet array to be plotted
 Brendon Watson, 2014
CROSS-REFERENCE INFORMATION
This function calls:
End Ending time of the intervalSet object
Start Starting times of for each interval in the set
plot makes a plot to represent an intervalset but simply plotting horizontal
This function is called by:
SOURCE CODE
function plotIntervals(intervals)
% % Plots a horizontal line showing timing of each interval in a set
%
% USAGE:
%     plotIntervals(x)
%
% INPUT:
%    x: intervalSet array to be plotted
%
% Brendon Watson, 2014
sta = Start(intervals);
sto = End(intervals);
plot([sta sto]',zeros(size([sta sto]')))