Description of plot
Home > @tsd > plot.m
plot
PURPOSE
Plots data in a TSD using time as x and data as y. If time = data (ie
SYNOPSIS
function plot(tsd)
DESCRIPTION
  Plots data in a TSD using time as x and data as y.  If time = data (ie
  for spikes data), plotting is done as a series of points.
      USAGE:
      plot(tsd)
      INPUTS:
      tsd - a tsd object
      OUTPUTS:
      [none]
 copyright (c) 2014 Brendon O. Watson
CROSS-REFERENCE INFORMATION
This function calls:
Data Returns Data of a TSD object
Range Returns TSD timestamps
plot Plots data in a TSD using time as x and data as y. If time = data (ie
size Return the size of the data component (overoad of the size function)
tsd Constructor of TSD object
This function is called by:
plot Plots data in a TSD using time as x and data as y. If time = data (ie
SOURCE CODE
function plot(tsd)
%  Plots data in a TSD using time as x and data as y.  If time = data (ie
%  for spikes data), plotting is done as a series of points.
%
%      USAGE:
%      plot(tsd)
%
%      INPUTS:
%      tsd - a tsd object
%
%      OUTPUTS:
%      [none]
% copyright (c) 2014 Brendon O. Watson
x = Range(tsd);
y = Data(tsd);
if sum(x-y)==0;
    y = zeros(size(x));
    plot(x,y,'.')
else
    plot(x,y);
end